### ISSUE TITLE
TypeError: Cannot read property 'Symbol(dartx._get)' of null

### ISSUE THREAD

**Issue by dexterBEN** [dexterBEN/GameBoard#5]
Appear when the list of games is loaded on homePage.

But the data is loaded anyway.

Details of the error:

Function.fromJson (http://localhost:54584/packages/gameboard_front/domain/entities/User.dart.lib.js:40:58)
    at Function.fromJson (http://localhost:54584/packages/gameboard_front/domain/entities/User.dart.lib.js:88:98)
    at http://localhost:54584/packages/gameboard_front/views/auth_view/login_form.dart.lib.js:435:40
    at _RootZone.runUnary (http://localhost:54584/dart_sdk.js:38385:58)
    at _FutureListener.then.handleValue (http://localhost:54584/dart_sdk.js:33375:29)
    at handleValueCallback (http://localhost:54584/dart_sdk.js:33923:49)
    at Function._propagateToListeners (http://localhost:54584/dart_sdk.js:33961:17)
    at _Future.new.[_completeWithValue] (http://localhost:54584/dart_sdk.js:33803:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54584/dart_sdk.js:33826:35)
    at Object._microtaskLoop (http://localhost:54584/dart_sdk.js:38643:13)
    at _startMicrotaskLoop (http://localhost:54584/dart_sdk.js:38649:13)
    at http://localhost:54584/dart_sdk.js:34176:9

**Comment by dexterBEN** [comment]
Resolved by update flutter to last version.
